// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeLedger.Data;

#nullable disable

namespace TradeLedger.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212144503_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("TradeLedger.Core.Models.Execution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fees")
                        .HasColumnType("REAL");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("Price")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("RawRowJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("Broker", "Account", "ExecutedAt", "Symbol");

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("TradeLedger.Core.Models.TradeGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LongStrike")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetPL")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Right")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Setup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShortStrike")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Broker", "Account", "Underlying", "Expiration", "Right", "ShortStrike", "LongStrike", "OpenDate")
                        .IsUnique();

                    b.ToTable("TradeGroups");
                });

            modelBuilder.Entity("TradeLedger.Core.Models.TradeGroupExecution", b =>
                {
                    b.Property<long>("TradeGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExecutionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TradeGroupId", "ExecutionId");

                    b.HasIndex("ExecutionId");

                    b.ToTable("TradeGroupExecutions");
                });

            modelBuilder.Entity("TradeLedger.Core.Models.TradeGroupLeg", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Right")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Strike")
                        .HasColumnType("TEXT");

                    b.Property<long>("TradeGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TradeGroupId");

                    b.ToTable("TradeGroupLegs");
                });

            modelBuilder.Entity("TradeLedger.Core.Models.TradeGroupExecution", b =>
                {
                    b.HasOne("TradeLedger.Core.Models.Execution", "Execution")
                        .WithMany()
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeLedger.Core.Models.TradeGroup", "TradeGroup")
                        .WithMany()
                        .HasForeignKey("TradeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");

                    b.Navigation("TradeGroup");
                });

            modelBuilder.Entity("TradeLedger.Core.Models.TradeGroupLeg", b =>
                {
                    b.HasOne("TradeLedger.Core.Models.TradeGroup", "TradeGroup")
                        .WithMany()
                        .HasForeignKey("TradeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
